# Generated by Django 4.0.4 on 2022-05-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='BirthdayDate',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='USDBalance',
            field=models.FloatField(default=100000),
        ),
    ]
